version: '3.3'

volumes:
  pg_project:

services:
  auth_db:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    ports:
      - "5432:5432"